"""

This file is a collection of functions that writes files for different functions form the oto libraries. Add more write function if needed by other function from different libraries.  
"""


def silence_detection_to_file(output_of_silence_detection, output_file_name, *args, **kwargs):

    """

    #TODO
    
    - Fill this with the documentation of the code. i.e. the docstring.

    - This function is to be called in the silence detection to save the output generated by it. 

    - Add arguments and functions, if needed.

    - Add requirements to requirements.txt usign "pip freeze > requirements.txt"

    - Let the user have option to choose different the output of the file format. (More info needed on this)



    """

def annotations_to_file(output_of_annotations, output_file, *args, **kwargs):

    """

    #TODO
    
    - Fill this with the documentation of the code. i.e. the docstring.

    - This function is to be called in the annotations function to save the output generated by it. 

    - Add arguments and functions, if needed.

    - Add requirements to requirements.txt usign "pip freeze > requirements.txt"

    - Let the user have option to choose different the output of the file format. (More info needed on this)

    """

def start_and_end_commands_to_file( output_from_function, output_file, *args, **kwargs):

    """

    #TODO
    
    - Fill this with the documentation of the code. i.e. the docstring.
    - This function is to be called in the start and end commands detection functions to save the output generated by it. 

    - Add arguments and functions, if needed.

    - Add requirements to requirements.txt usign "pip freeze > requirements.txt"

    - Let the user have option to choose different the output of the file format. (More info needed on this)

    """


